







CREATE ROLE uaded WITH
	INHERIT
	LOGIN
	ENCRYPTED PASSWORD '********';


















CREATE TABLE public.grado (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	grado character varying(255) NOT NULL,
	nivel character varying(150) NOT NULL,
	ges_id integer NOT NULL,
	creado date NOT NULL,
	act date NOT NULL,
	usu_id integer NOT NULL,
	CONSTRAINT gra_pkey PRIMARY KEY (id)

);

ALTER TABLE public.grado OWNER TO uaded;


















CREATE TABLE public.materia (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	materia character varying(150) NOT NULL,
	gra_id integer NOT NULL,
	creado date NOT NULL,
	act date NOT NULL,
	usu_id integer NOT NULL,
	CONSTRAINT mat_pkey PRIMARY KEY (id)

);

ALTER TABLE public.materia OWNER TO uaded;


















CREATE TABLE public.alumno (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	nombre character varying(100) NOT NULL,
	paterno character varying(100),
	materno character varying(100),
	nacimiento date,
	masculino boolean NOT NULL,
	ci integer,
	direccion character varying(150),
	email varchar(100),
	activo boolean NOT NULL,
	obs character varying(100),
	usr_id_login integer,
	foto_ruta varchar(150),
	creado date NOT NULL,
	act date NOT NULL,
	usu_id integer NOT NULL,
	CONSTRAINT alu_pk PRIMARY KEY (id)

);

ALTER TABLE public.alumno OWNER TO uaded;


















CREATE TABLE public.inscrito (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	alu_id integer,
	cur_id integer,
	reserva boolean,
	inscrito boolean NOT NULL,
	descuento smallint NOT NULL,
	motivo_descuento character varying(100),
	abandono boolean NOT NULL DEFAULT false,
	obs character varying(200),
	creado date NOT NULL,
	act date NOT NULL,
	usu_id integer NOT NULL,
	CONSTRAINT ins_pk PRIMARY KEY (id),
	CONSTRAINT ins_uq UNIQUE (alu_id)

);

COMMENT ON TABLE public.inscrito IS E'Alumno inscrito';

COMMENT ON COLUMN public.inscrito.descuento IS E'% descuento';

ALTER TABLE public.inscrito OWNER TO uaded;


















CREATE TABLE public.curso (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	curso character varying(150),
	paralelo character varying(50) NOT NULL,
	gra_id integer NOT NULL,
	aula character varying(50),
	capacidad smallint,
	gestion smallint NOT NULL,
	creado date NOT NULL,
	act date NOT NULL,
	usu_id integer NOT NULL,
	CONSTRAINT cur_pk PRIMARY KEY (id)

);

ALTER TABLE public.curso OWNER TO uaded;


















CREATE TABLE public.nota (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	ins_id integer NOT NULL,
	mat_id integer NOT NULL,
	nota1 smallint NOT NULL,
	nota2 smallint NOT NULL,
	nota3 smallint NOT NULL,
	nota_final numeric(5,1) NOT NULL,
	nota_aprob smallint NOT NULL,
	aprobado boolean,
	obs character varying(150),
	creado date NOT NULL,
	act date NOT NULL,
	usu_id integer NOT NULL,
	CONSTRAINT cal_pk PRIMARY KEY (id)

);

COMMENT ON TABLE public.nota IS E'SEGuimiento académico';

ALTER TABLE public.nota OWNER TO uaded;


















CREATE TABLE public.profesor (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	nombre character varying(100) NOT NULL,
	paterno character varying(50),
	materno character varying(50),
	masculino boolean NOT NULL,
	ci integer,
	formacion character varying(100),
	email varchar(100),
	activo boolean NOT NULL,
	usr_id_login integer,
	creado date NOT NULL,
	act date NOT NULL,
	usu_id integer NOT NULL,
	CONSTRAINT pro_pk PRIMARY KEY (id)

);

ALTER TABLE public.profesor OWNER TO uaded;


















CREATE TABLE public.asignado (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	cur_id integer NOT NULL,
	mat_id integer NOT NULL,
	pro_id integer NOT NULL,
	creado date NOT NULL,
	act date NOT NULL,
	usu_id integer NOT NULL,
	CONSTRAINT asi_pk PRIMARY KEY (id)

);

COMMENT ON TABLE public.asignado IS E'prof asignado enseña a un curso y  materias asignadas';

ALTER TABLE public.asignado OWNER TO uaded;


















CREATE TABLE public.pago (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	ins_id integer NOT NULL,
	nro_cuota smallint NOT NULL,
	cuota double precision NOT NULL,
	pagado boolean,
	metodo_pago character varying(50),
	fecha_pago date,
	referencia_pago character varying(100),
	obs character varying(100),
	creado date NOT NULL,
	act date NOT NULL,
	usu_id integer NOT NULL
);

ALTER TABLE public.pago OWNER TO uaded;


















CREATE TABLE public.costo (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	cur_id integer NOT NULL,
	nro_cuota smallint NOT NULL,
	cuota numeric(10,2) NOT NULL,
	obs character varying(200) NOT NULL,
	creado date NOT NULL,
	act date NOT NULL,
	usu_id integer NOT NULL,
	CONSTRAINT cos_pk PRIMARY KEY (id)

);

ALTER TABLE public.costo OWNER TO uaded;


















CREATE TABLE public.gestion (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	gestion smallint,
	plan character varying(150) NOT NULL,
	inicio date NOT NULL,
	fin date NOT NULL,
	activo boolean NOT NULL,
	creado date NOT NULL,
	act date NOT NULL,
	usu_id integer NOT NULL,
	CONSTRAINT ges_pk PRIMARY KEY (id)

);

ALTER TABLE public.gestion OWNER TO uaded;


















CREATE SEQUENCE public.usr_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START WITH 1
	CACHE 1
	NO CYCLE
	OWNED BY NONE;

ALTER SEQUENCE public.usr_id_seq OWNER TO uaded;




CREATE TABLE public.usuario (
	id integer NOT NULL DEFAULT nextval('public.usr_id_seq'::regclass),
	usuario character varying(80) NOT NULL,
	email character varying(100) NOT NULL,
	password character varying(255) NOT NULL,
	activo boolean,
	last_login date NOT NULL,
	creado timestamp,
	act timestamp,
	CONSTRAINT usr_pkey PRIMARY KEY (id)

);

ALTER TABLE public.usuario OWNER TO uaded;




CREATE UNIQUE INDEX ix_usr_usuario ON public.usuario
	USING btree
	(
	  usuario
	)
	WITH (FILLFACTOR = 90);




CREATE SEQUENCE public.rol_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START WITH 1
	CACHE 1
	NO CYCLE
	OWNED BY NONE;

ALTER SEQUENCE public.rol_id_seq OWNER TO uaded;




CREATE TABLE public.rol (
	id integer NOT NULL DEFAULT nextval('public.rol_id_seq'::regclass),
	rol character varying(50) NOT NULL,
	descripcion character varying(255),
	creado timestamp,
	act date,
	CONSTRAINT rol_pkey PRIMARY KEY (id),
	CONSTRAINT rol_rol_key UNIQUE (rol)

);

ALTER TABLE public.rol OWNER TO uaded;




CREATE SEQUENCE public.per_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START WITH 1
	CACHE 1
	NO CYCLE
	OWNED BY NONE;

ALTER SEQUENCE public.per_id_seq OWNER TO uaded;




CREATE TABLE public.permiso (
	id integer NOT NULL DEFAULT nextval('public.per_id_seq'::regclass),
	permiso character varying(50) NOT NULL,
	descripcion character varying(255),
	creado timestamp,
	act timestamp,
	CONSTRAINT per_pkey PRIMARY KEY (id),
	CONSTRAINT per_permiso_key UNIQUE (permiso)

);

ALTER TABLE public.permiso OWNER TO uaded;




CREATE TABLE public.usuario_rol (
	usu_id integer NOT NULL,
	rol_id integer NOT NULL,
	CONSTRAINT usr_rol_pkey PRIMARY KEY (usu_id,rol_id)

);

ALTER TABLE public.usuario_rol OWNER TO uaded;




CREATE TABLE public.rol_permiso (
	rol_id integer NOT NULL,
	per_id integer NOT NULL,
	CONSTRAINT rol_per_pkey PRIMARY KEY (rol_id,per_id)

);

ALTER TABLE public.rol_permiso OWNER TO uaded;




ALTER TABLE public.grado ADD CONSTRAINT ges_fk FOREIGN KEY (ges_id)
REFERENCES public.gestion (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;




ALTER TABLE public.materia ADD CONSTRAINT mat_id_gra_fkey FOREIGN KEY (gra_id)
REFERENCES public.grado (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;




ALTER TABLE public.inscrito ADD CONSTRAINT alu_fk FOREIGN KEY (alu_id)
REFERENCES public.alumno (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;




ALTER TABLE public.inscrito ADD CONSTRAINT cur_fk FOREIGN KEY (cur_id)
REFERENCES public.curso (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;




ALTER TABLE public.curso ADD CONSTRAINT gra_fk FOREIGN KEY (gra_id)
REFERENCES public.grado (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;




ALTER TABLE public.nota ADD CONSTRAINT ins_fk FOREIGN KEY (ins_id)
REFERENCES public.inscrito (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;




ALTER TABLE public.asignado ADD CONSTRAINT pro_fk FOREIGN KEY (pro_id)
REFERENCES public.profesor (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;




ALTER TABLE public.asignado ADD CONSTRAINT cur_fk FOREIGN KEY (cur_id)
REFERENCES public.curso (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;




ALTER TABLE public.asignado ADD CONSTRAINT mat_fk FOREIGN KEY (mat_id)
REFERENCES public.materia (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;




ALTER TABLE public.pago ADD CONSTRAINT insc_fk FOREIGN KEY (ins_id)
REFERENCES public.inscrito (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;




ALTER TABLE public.costo ADD CONSTRAINT cur_fk FOREIGN KEY (cur_id)
REFERENCES public.curso (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;




ALTER TABLE public.usuario_rol ADD CONSTRAINT usr_rol_usr_id_fkey FOREIGN KEY (usu_id)
REFERENCES public.usuario (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;




ALTER TABLE public.usuario_rol ADD CONSTRAINT usr_rol_rol_id_fkey FOREIGN KEY (rol_id)
REFERENCES public.rol (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;




ALTER TABLE public.rol_permiso ADD CONSTRAINT rol_per_rol_id_fkey FOREIGN KEY (rol_id)
REFERENCES public.rol (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;




ALTER TABLE public.rol_permiso ADD CONSTRAINT rol_per_per_id_fkey FOREIGN KEY (per_id)
REFERENCES public.permiso (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;



