-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler  version: 0.9.2
-- PostgreSQL version: 12.0
-- Project Site: pgmodeler.io
-- Model Author: ---

-- object: uaded | type: ROLE --
-- DROP ROLE IF EXISTS uaded;
CREATE ROLE uaded WITH 
	INHERIT
	LOGIN
	ENCRYPTED PASSWORD '********';
-- ddl-end --


-- Database creation must be done outside a multicommand file.
-- These commands were put in this file only as a convenience.
-- -- object: dbaded1 | type: DATABASE --
-- -- DROP DATABASE IF EXISTS dbaded1;
-- CREATE DATABASE dbaded1
-- 	ENCODING = 'UTF8'
-- 	LC_COLLATE = 'en_US.UTF-8'
-- 	LC_CTYPE = 'en_US.UTF-8'
-- 	TABLESPACE = pg_default
-- 	OWNER = uaded;
-- -- ddl-end --
-- 

-- object: public.pla | type: TABLE --
-- DROP TABLE IF EXISTS public.pla CASCADE;
CREATE TABLE public.pla (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	plan character varying(150) NOT NULL,
	CONSTRAINT pla_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.pla OWNER TO uaded;
-- ddl-end --

-- -- object: public.pla_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.pla_id_seq CASCADE;
-- CREATE SEQUENCE public.pla_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.pla_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.niv | type: TABLE --
-- DROP TABLE IF EXISTS public.niv CASCADE;
CREATE TABLE public.niv (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	nivel character varying(255) NOT NULL,
	pla_id integer NOT NULL,
	CONSTRAINT niv_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.niv OWNER TO uaded;
-- ddl-end --

-- -- object: public.niv_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.niv_id_seq CASCADE;
-- CREATE SEQUENCE public.niv_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.niv_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.gra | type: TABLE --
-- DROP TABLE IF EXISTS public.gra CASCADE;
CREATE TABLE public.gra (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	grado character varying(255) NOT NULL,
	niv_id integer NOT NULL,
	CONSTRAINT gra_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.gra OWNER TO uaded;
-- ddl-end --

-- -- object: public.gra_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.gra_id_seq CASCADE;
-- CREATE SEQUENCE public.gra_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.gra_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.mat | type: TABLE --
-- DROP TABLE IF EXISTS public.mat CASCADE;
CREATE TABLE public.mat (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	materia character varying(150) NOT NULL,
	gra_id integer NOT NULL,
	CONSTRAINT mat_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.mat OWNER TO uaded;
-- ddl-end --

-- -- object: public.mat_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.mat_id_seq CASCADE;
-- CREATE SEQUENCE public.mat_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.mat_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.alu | type: TABLE --
-- DROP TABLE IF EXISTS public.alu CASCADE;
CREATE TABLE public.alu (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	nombre character varying(100) NOT NULL,
	apellido character varying(100) NOT NULL,
	CONSTRAINT alu_pk PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.alu OWNER TO uaded;
-- ddl-end --

-- -- object: public.alu_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.alu_id_seq CASCADE;
-- CREATE SEQUENCE public.alu_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.alu_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.ins | type: TABLE --
-- DROP TABLE IF EXISTS public.ins CASCADE;
CREATE TABLE public.ins (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	alu_id integer,
	cur_id integer,
	cos_id integer NOT NULL,
	fecha_ins date,
	CONSTRAINT ins_pk PRIMARY KEY (id),
	CONSTRAINT ins_uq UNIQUE (alu_id)

);
-- ddl-end --
ALTER TABLE public.ins OWNER TO uaded;
-- ddl-end --

-- -- object: public.ins_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.ins_id_seq CASCADE;
-- CREATE SEQUENCE public.ins_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.ins_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.cur | type: TABLE --
-- DROP TABLE IF EXISTS public.cur CASCADE;
CREATE TABLE public.cur (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	gra_id integer NOT NULL,
	paralelo character varying(50) NOT NULL,
	gestion smallint NOT NULL,
	fecha_ini date,
	fecha_fin date,
	CONSTRAINT cur_pk PRIMARY KEY (id)

);
-- ddl-end --
COMMENT ON COLUMN public.cur.fecha_ini IS E'con datos cuando es diferente a una gestión anual';
-- ddl-end --
COMMENT ON COLUMN public.cur.fecha_fin IS E'con datos cuando es diferente a una gestión anual';
-- ddl-end --
ALTER TABLE public.cur OWNER TO uaded;
-- ddl-end --

-- -- object: public.cur_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.cur_id_seq CASCADE;
-- CREATE SEQUENCE public.cur_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.cur_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.seg | type: TABLE --
-- DROP TABLE IF EXISTS public.seg CASCADE;
CREATE TABLE public.seg (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	ins_id integer NOT NULL,
	mat_id integer NOT NULL,
	ev01 smallint,
	ev02 smallint,
	evfin smallint,
	aprob boolean,
	CONSTRAINT seg_pk PRIMARY KEY (id)

);
-- ddl-end --
COMMENT ON TABLE public.seg IS E'SEGuimiento académico';
-- ddl-end --
ALTER TABLE public.seg OWNER TO uaded;
-- ddl-end --

-- -- object: public.seg_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.seg_id_seq CASCADE;
-- CREATE SEQUENCE public.seg_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.seg_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.pro | type: TABLE --
-- DROP TABLE IF EXISTS public.pro CASCADE;
CREATE TABLE public.pro (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	nombre character varying(100) NOT NULL,
	apellido character varying(100) NOT NULL,
	formacion character varying(100),
	CONSTRAINT pro_pk PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.pro OWNER TO uaded;
-- ddl-end --

-- -- object: public.pro_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.pro_id_seq CASCADE;
-- CREATE SEQUENCE public.pro_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.pro_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.asi | type: TABLE --
-- DROP TABLE IF EXISTS public.asi CASCADE;
CREATE TABLE public.asi (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	cur_id integer NOT NULL,
	mat_id integer NOT NULL,
	pro_id integer NOT NULL,
	CONSTRAINT asi_pk PRIMARY KEY (id)

);
-- ddl-end --
COMMENT ON TABLE public.asi IS E'prof ASIgnado (enseña) a un curso y descripción de materias asignadas';
-- ddl-end --
ALTER TABLE public.asi OWNER TO uaded;
-- ddl-end --

-- -- object: public.asi_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.asi_id_seq CASCADE;
-- CREATE SEQUENCE public.asi_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.asi_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.pag | type: TABLE --
-- DROP TABLE IF EXISTS public.pag CASCADE;
CREATE TABLE public.pag (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	ins_id integer NOT NULL,
	cuota double precision NOT NULL,
	nro_cuota smallint NOT NULL,
	pagado boolean,
	fecha_pago date,
	obs character varying(100)
);
-- ddl-end --
ALTER TABLE public.pag OWNER TO uaded;
-- ddl-end --

-- -- object: public.pag_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.pag_id_seq CASCADE;
-- CREATE SEQUENCE public.pag_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.pag_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.cos | type: TABLE --
-- DROP TABLE IF EXISTS public.cos CASCADE;
CREATE TABLE public.cos (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	descrip character varying(200) NOT NULL,
	costo double precision NOT NULL,
	descu smallint NOT NULL,
	cuota double precision NOT NULL,
	nro smallint NOT NULL,
	importe double precision NOT NULL,
	CONSTRAINT cos_pk PRIMARY KEY (id)

);
-- ddl-end --
COMMENT ON COLUMN public.cos.descu IS E'%';
-- ddl-end --
ALTER TABLE public.cos OWNER TO uaded;
-- ddl-end --

-- -- object: public.cos_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.cos_id_seq CASCADE;
-- CREATE SEQUENCE public.cos_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.cos_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: niv_id_plan_fkey | type: CONSTRAINT --
-- ALTER TABLE public.niv DROP CONSTRAINT IF EXISTS niv_id_plan_fkey CASCADE;
ALTER TABLE public.niv ADD CONSTRAINT niv_id_plan_fkey FOREIGN KEY (pla_id)
REFERENCES public.pla (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: gra_id_niv_fkey | type: CONSTRAINT --
-- ALTER TABLE public.gra DROP CONSTRAINT IF EXISTS gra_id_niv_fkey CASCADE;
ALTER TABLE public.gra ADD CONSTRAINT gra_id_niv_fkey FOREIGN KEY (niv_id)
REFERENCES public.niv (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: mat_id_gra_fkey | type: CONSTRAINT --
-- ALTER TABLE public.mat DROP CONSTRAINT IF EXISTS mat_id_gra_fkey CASCADE;
ALTER TABLE public.mat ADD CONSTRAINT mat_id_gra_fkey FOREIGN KEY (gra_id)
REFERENCES public.gra (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: cos_fk | type: CONSTRAINT --
-- ALTER TABLE public.ins DROP CONSTRAINT IF EXISTS cos_fk CASCADE;
ALTER TABLE public.ins ADD CONSTRAINT cos_fk FOREIGN KEY (cos_id)
REFERENCES public.cos (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: alu_fk | type: CONSTRAINT --
-- ALTER TABLE public.ins DROP CONSTRAINT IF EXISTS alu_fk CASCADE;
ALTER TABLE public.ins ADD CONSTRAINT alu_fk FOREIGN KEY (alu_id)
REFERENCES public.alu (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: cur_fk | type: CONSTRAINT --
-- ALTER TABLE public.ins DROP CONSTRAINT IF EXISTS cur_fk CASCADE;
ALTER TABLE public.ins ADD CONSTRAINT cur_fk FOREIGN KEY (cur_id)
REFERENCES public.cur (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: gra_fk | type: CONSTRAINT --
-- ALTER TABLE public.cur DROP CONSTRAINT IF EXISTS gra_fk CASCADE;
ALTER TABLE public.cur ADD CONSTRAINT gra_fk FOREIGN KEY (gra_id)
REFERENCES public.gra (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: ins_fk | type: CONSTRAINT --
-- ALTER TABLE public.seg DROP CONSTRAINT IF EXISTS ins_fk CASCADE;
ALTER TABLE public.seg ADD CONSTRAINT ins_fk FOREIGN KEY (ins_id)
REFERENCES public.ins (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: pro_fk | type: CONSTRAINT --
-- ALTER TABLE public.asi DROP CONSTRAINT IF EXISTS pro_fk CASCADE;
ALTER TABLE public.asi ADD CONSTRAINT pro_fk FOREIGN KEY (pro_id)
REFERENCES public.pro (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: cur_fk | type: CONSTRAINT --
-- ALTER TABLE public.asi DROP CONSTRAINT IF EXISTS cur_fk CASCADE;
ALTER TABLE public.asi ADD CONSTRAINT cur_fk FOREIGN KEY (cur_id)
REFERENCES public.cur (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: mat_fk | type: CONSTRAINT --
-- ALTER TABLE public.asi DROP CONSTRAINT IF EXISTS mat_fk CASCADE;
ALTER TABLE public.asi ADD CONSTRAINT mat_fk FOREIGN KEY (mat_id)
REFERENCES public.mat (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: insc_fk | type: CONSTRAINT --
-- ALTER TABLE public.pag DROP CONSTRAINT IF EXISTS insc_fk CASCADE;
ALTER TABLE public.pag ADD CONSTRAINT insc_fk FOREIGN KEY (ins_id)
REFERENCES public.ins (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --


