-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler  version: 0.9.2
-- PostgreSQL version: 12.0
-- Project Site: pgmodeler.io
-- Model Author: ---

-- object: uaded | type: ROLE --
-- DROP ROLE IF EXISTS uaded;
CREATE ROLE uaded WITH 
	INHERIT
	LOGIN
	UNENCRYPTED PASSWORD '********';
-- ddl-end --


-- Database creation must be done outside a multicommand file.
-- These commands were put in this file only as a convenience.
-- -- object: dbaded | type: DATABASE --
-- -- DROP DATABASE IF EXISTS dbaded;
-- CREATE DATABASE dbaded
-- 	ENCODING = 'UTF8'
-- 	LC_COLLATE = 'en_US.UTF-8'
-- 	LC_CTYPE = 'en_US.UTF-8'
-- 	TABLESPACE = pg_default
-- 	OWNER = uaded;
-- -- ddl-end --
-- 

-- object: public.plan | type: TABLE --
-- DROP TABLE IF EXISTS public.plan CASCADE;
CREATE TABLE public.plan (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	plan character varying(150) NOT NULL,
	CONSTRAINT plan_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.plan OWNER TO uaded;
-- ddl-end --

-- -- object: public.plan_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.plan_id_seq CASCADE;
-- CREATE SEQUENCE public.plan_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.plan_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.nivel | type: TABLE --
-- DROP TABLE IF EXISTS public.nivel CASCADE;
CREATE TABLE public.nivel (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	nivel character varying(255) NOT NULL,
	plan_id integer NOT NULL,
	CONSTRAINT nivel_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.nivel OWNER TO uaded;
-- ddl-end --

-- -- object: public.nivel_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.nivel_id_seq CASCADE;
-- CREATE SEQUENCE public.nivel_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.nivel_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.grado | type: TABLE --
-- DROP TABLE IF EXISTS public.grado CASCADE;
CREATE TABLE public.grado (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	grado character varying(255) NOT NULL,
	nivel_id integer NOT NULL,
	CONSTRAINT grado_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.grado OWNER TO uaded;
-- ddl-end --

-- -- object: public.grado_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.grado_id_seq CASCADE;
-- CREATE SEQUENCE public.grado_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.grado_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.mat | type: TABLE --
-- DROP TABLE IF EXISTS public.mat CASCADE;
CREATE TABLE public.mat (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	materia character varying(150) NOT NULL,
	grado_id integer NOT NULL,
	CONSTRAINT materia_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.mat OWNER TO uaded;
-- ddl-end --

-- -- object: public.materia_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.materia_id_seq CASCADE;
-- CREATE SEQUENCE public.materia_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.materia_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.alum | type: TABLE --
-- DROP TABLE IF EXISTS public.alum CASCADE;
CREATE TABLE public.alum (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	nombre character varying(100) NOT NULL,
	apellido character varying(100) NOT NULL,
	CONSTRAINT alum_pk PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.alum OWNER TO uaded;
-- ddl-end --

-- -- object: public.alum_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.alum_id_seq CASCADE;
-- CREATE SEQUENCE public.alum_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.alum_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.insc | type: TABLE --
-- DROP TABLE IF EXISTS public.insc CASCADE;
CREATE TABLE public.insc (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	alum_id integer,
	curso_id integer,
	fecha_insc date,
	CONSTRAINT insc_pk PRIMARY KEY (id),
	CONSTRAINT insc_uq UNIQUE (alum_id)

);
-- ddl-end --
ALTER TABLE public.insc OWNER TO uaded;
-- ddl-end --

-- -- object: public.inscripcion_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.inscripcion_id_seq CASCADE;
-- CREATE SEQUENCE public.inscripcion_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.inscripcion_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.curso | type: TABLE --
-- DROP TABLE IF EXISTS public.curso CASCADE;
CREATE TABLE public.curso (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	grado_id integer NOT NULL,
	paralelo character varying(50),
	gestion smallint,
	fecha_ini date,
	fecha_fin date,
	CONSTRAINT curso_pk PRIMARY KEY (id)

);
-- ddl-end --
COMMENT ON COLUMN public.curso.fecha_ini IS E'con datos cuando es diferente a una gestión anual';
-- ddl-end --
COMMENT ON COLUMN public.curso.fecha_fin IS E'con datos cuando es diferente a una gestión anual';
-- ddl-end --
ALTER TABLE public.curso OWNER TO uaded;
-- ddl-end --

-- -- object: public.curso_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.curso_id_seq CASCADE;
-- CREATE SEQUENCE public.curso_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.curso_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.seg | type: TABLE --
-- DROP TABLE IF EXISTS public.seg CASCADE;
CREATE TABLE public.seg (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	insc_id integer NOT NULL,
	alum_id integer NOT NULL,
	mat_id smallint NOT NULL,
	ev01 smallint,
	ev02 smallint,
	ev03 smallint,
	evfin smallint,
	aprob boolean,
	CONSTRAINT seg_pk PRIMARY KEY (id)

);
-- ddl-end --
COMMENT ON TABLE public.seg IS E'SEGuimiento académico';
-- ddl-end --
COMMENT ON COLUMN public.seg.mat_id IS E'asignado a partir de INSC/CURSO/ASIG.id_mat';
-- ddl-end --
ALTER TABLE public.seg OWNER TO uaded;
-- ddl-end --

-- object: public.prof | type: TABLE --
-- DROP TABLE IF EXISTS public.prof CASCADE;
CREATE TABLE public.prof (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	nombre varchar(100),
	apellido varchar(100),
	formacion varchar(100),
	CONSTRAINT prof_pk PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.prof OWNER TO uaded;
-- ddl-end --

-- object: public.asig | type: TABLE --
-- DROP TABLE IF EXISTS public.asig CASCADE;
CREATE TABLE public.asig (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	prof_id integer NOT NULL,
	curso_id integer NOT NULL,
	mat_id integer NOT NULL,
	CONSTRAINT asig_pk PRIMARY KEY (id)

);
-- ddl-end --
COMMENT ON TABLE public.asig IS E'prof ASIGnado (enseña) a un curso y descripción de materias asignadas';
-- ddl-end --
ALTER TABLE public.asig OWNER TO uaded;
-- ddl-end --

-- object: prof_fk | type: CONSTRAINT --
-- ALTER TABLE public.asig DROP CONSTRAINT IF EXISTS prof_fk CASCADE;
ALTER TABLE public.asig ADD CONSTRAINT prof_fk FOREIGN KEY (prof_id)
REFERENCES public.prof (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: curso_fk | type: CONSTRAINT --
-- ALTER TABLE public.asig DROP CONSTRAINT IF EXISTS curso_fk CASCADE;
ALTER TABLE public.asig ADD CONSTRAINT curso_fk FOREIGN KEY (curso_id)
REFERENCES public.curso (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: mat_fk | type: CONSTRAINT --
-- ALTER TABLE public.asig DROP CONSTRAINT IF EXISTS mat_fk CASCADE;
ALTER TABLE public.asig ADD CONSTRAINT mat_fk FOREIGN KEY (mat_id)
REFERENCES public.mat (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: insc_fk | type: CONSTRAINT --
-- ALTER TABLE public.seg DROP CONSTRAINT IF EXISTS insc_fk CASCADE;
ALTER TABLE public.seg ADD CONSTRAINT insc_fk FOREIGN KEY (insc_id)
REFERENCES public.insc (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: nivel_id_plan_fkey | type: CONSTRAINT --
-- ALTER TABLE public.nivel DROP CONSTRAINT IF EXISTS nivel_id_plan_fkey CASCADE;
ALTER TABLE public.nivel ADD CONSTRAINT nivel_id_plan_fkey FOREIGN KEY (plan_id)
REFERENCES public.plan (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: grado_id_nivel_fkey | type: CONSTRAINT --
-- ALTER TABLE public.grado DROP CONSTRAINT IF EXISTS grado_id_nivel_fkey CASCADE;
ALTER TABLE public.grado ADD CONSTRAINT grado_id_nivel_fkey FOREIGN KEY (nivel_id)
REFERENCES public.nivel (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: materia_id_grado_fkey | type: CONSTRAINT --
-- ALTER TABLE public.mat DROP CONSTRAINT IF EXISTS materia_id_grado_fkey CASCADE;
ALTER TABLE public.mat ADD CONSTRAINT materia_id_grado_fkey FOREIGN KEY (grado_id)
REFERENCES public.grado (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: alum_fk | type: CONSTRAINT --
-- ALTER TABLE public.insc DROP CONSTRAINT IF EXISTS alum_fk CASCADE;
ALTER TABLE public.insc ADD CONSTRAINT alum_fk FOREIGN KEY (alum_id)
REFERENCES public.alum (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: curso_fk | type: CONSTRAINT --
-- ALTER TABLE public.insc DROP CONSTRAINT IF EXISTS curso_fk CASCADE;
ALTER TABLE public.insc ADD CONSTRAINT curso_fk FOREIGN KEY (curso_id)
REFERENCES public.curso (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: grado_fk | type: CONSTRAINT --
-- ALTER TABLE public.curso DROP CONSTRAINT IF EXISTS grado_fk CASCADE;
ALTER TABLE public.curso ADD CONSTRAINT grado_fk FOREIGN KEY (grado_id)
REFERENCES public.grado (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --


