CREATE TABLE public.plan (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	plan character varying(150) NOT NULL,
	CONSTRAINT plan_pkey PRIMARY KEY (id)

);
CREATE TABLE public.nivel (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	nivel character varying(255) NOT NULL,
	id_plan integer NOT NULL,
	CONSTRAINT nivel_pkey PRIMARY KEY (id)

);
CREATE TABLE public.grado (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	grado character varying(255) NOT NULL,
	id_nivel integer NOT NULL,
	CONSTRAINT grado_pkey PRIMARY KEY (id)

);
CREATE TABLE public.mat (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	materia character varying(150) NOT NULL,
	id_grado integer NOT NULL,
	CONSTRAINT materia_pkey PRIMARY KEY (id)

);
CREATE TABLE public.alum (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	nombre character varying(100) NOT NULL,
	paterno character varying(100) NOT NULL,
	CONSTRAINT alum_pk PRIMARY KEY (id)

);
CREATE TABLE public.insc (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	id_alum integer,
	id_curso integer,
	fecha_insc date,
	CONSTRAINT insc_pk PRIMARY KEY (id),
	CONSTRAINT insc_uq UNIQUE (id_alum)

);
CREATE TABLE public.curso (
	id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	paralelo character varying(50),
	id_grado integer NOT NULL,
	gestion smallint,
	fecha_ini date,
	fecha_fin date,
	CONSTRAINT curso_pk PRIMARY KEY (id)

);
CREATE TABLE public.seg (
	id integer NOT NULL,
	id_alum integer NOT NULL,
	id_insc integer NOT NULL,
	id_mat smallint NOT NULL,
	ev01 smallint,
	ev02 smallint,
	ev03 smallint,
	evfin smallint,
	aprob boolean,
	CONSTRAINT seg_pk PRIMARY KEY (id)

);

CREATE TABLE public.prof (
	id integer NOT NULL,
	nom_prof varchar(100),
	formacion varchar(100),
	CONSTRAINT prof_pk PRIMARY KEY (id)

);

CREATE TABLE public.asig (
	id integer NOT NULL,
	id_prof integer NOT NULL,
	id_mat integer NOT NULL,
	id_curso integer NOT NULL,
	CONSTRAINT asig_pk PRIMARY KEY (id)

);


CREATE UNIQUE INDEX prof_mat_curso ON public.asig
	USING btree
	(
	  id_prof,
	  id_mat,
	  id_curso
	);

ALTER TABLE public.nivel ADD CONSTRAINT nivel_id_plan_fkey FOREIGN KEY (id_plan)
REFERENCES public.plan (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.grado ADD CONSTRAINT grado_id_nivel_fkey FOREIGN KEY (id_nivel)
REFERENCES public.nivel (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.mat ADD CONSTRAINT materia_id_grado_fkey FOREIGN KEY (id_grado)
REFERENCES public.grado (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;


ALTER TABLE public.asig ADD CONSTRAINT prof_fk FOREIGN KEY (id_prof)
REFERENCES public.prof (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.asig ADD CONSTRAINT mat_fk FOREIGN KEY (id_mat)
REFERENCES public.mat (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.asig ADD CONSTRAINT curso_fk FOREIGN KEY (id_curso)
REFERENCES public.curso (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;


ALTER TABLE public.curso ADD CONSTRAINT grado_fk FOREIGN KEY (id_grado)
REFERENCES public.grado (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.seg ADD CONSTRAINT insc_fk FOREIGN KEY (id_insc)
REFERENCES public.insc (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.insc ADD CONSTRAINT alum_fk FOREIGN KEY (id_alum)
REFERENCES public.alum (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE public.insc ADD CONSTRAINT curso_fk FOREIGN KEY (id_curso)
REFERENCES public.curso (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;

