-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler  version: 0.9.2
-- PostgreSQL version: 12.0
-- Project Site: pgmodeler.io
-- Model Author: ---

-- object: uaded | type: ROLE --
-- DROP ROLE IF EXISTS uaded;
CREATE ROLE uaded WITH 
	INHERIT
	LOGIN
	ENCRYPTED PASSWORD '********';
-- ddl-end --


-- Database creation must be done outside a multicommand file.
-- These commands were put in this file only as a convenience.
-- -- object: dbaded1 | type: DATABASE --
-- -- DROP DATABASE IF EXISTS dbaded1;
-- CREATE DATABASE dbaded1
-- 	ENCODING = 'UTF8'
-- 	LC_COLLATE = 'en_US.UTF-8'
-- 	LC_CTYPE = 'en_US.UTF-8'
-- 	TABLESPACE = pg_default
-- 	OWNER = uaded;
-- -- ddl-end --
-- 

-- -- object: public.pla_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.pla_id_seq CASCADE;
-- CREATE SEQUENCE public.pla_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.pla_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- -- object: public.niv_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.niv_id_seq CASCADE;
-- CREATE SEQUENCE public.niv_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.niv_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.gra | type: TABLE --
-- DROP TABLE IF EXISTS public.gra CASCADE;
CREATE TABLE public.gra (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	grado character varying(255) NOT NULL,
	nivel varchar(150) NOT NULL,
	id_ges integer NOT NULL,
	creado date NOT NULL,
	act date NOT NULL,
	CONSTRAINT gra_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.gra OWNER TO uaded;
-- ddl-end --

-- -- object: public.gra_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.gra_id_seq CASCADE;
-- CREATE SEQUENCE public.gra_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.gra_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.mat | type: TABLE --
-- DROP TABLE IF EXISTS public.mat CASCADE;
CREATE TABLE public.mat (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	materia character varying(150) NOT NULL,
	gra_id integer NOT NULL,
	creado date NOT NULL,
	act date NOT NULL,
	CONSTRAINT mat_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.mat OWNER TO uaded;
-- ddl-end --

-- -- object: public.mat_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.mat_id_seq CASCADE;
-- CREATE SEQUENCE public.mat_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.mat_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.est | type: TABLE --
-- DROP TABLE IF EXISTS public.est CASCADE;
CREATE TABLE public.est (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	nombre character varying(100) NOT NULL,
	paterno character varying(100),
	materno varchar(100),
	nacimiento date,
	masculino boolean NOT NULL,
	ci integer,
	direccion varchar(150),
	activo boolean NOT NULL,
	obs varchar(100),
	creado date NOT NULL,
	act date NOT NULL,
	CONSTRAINT alu_pk PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.est OWNER TO uaded;
-- ddl-end --

-- -- object: public.alu_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.alu_id_seq CASCADE;
-- CREATE SEQUENCE public.alu_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.alu_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.ins | type: TABLE --
-- DROP TABLE IF EXISTS public.ins CASCADE;
CREATE TABLE public.ins (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	est_id integer,
	cur_id integer,
	reserva boolean,
	inscrito boolean NOT NULL,
	descu smallint NOT NULL,
	motivo_descu varchar(100),
	abandono boolean NOT NULL DEFAULT False,
	obs varchar(200),
	creado date NOT NULL,
	act date NOT NULL,
	CONSTRAINT ins_pk PRIMARY KEY (id),
	CONSTRAINT ins_uq UNIQUE (est_id)

);
-- ddl-end --
ALTER TABLE public.ins OWNER TO uaded;
-- ddl-end --

-- -- object: public.ins_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.ins_id_seq CASCADE;
-- CREATE SEQUENCE public.ins_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.ins_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.cur | type: TABLE --
-- DROP TABLE IF EXISTS public.cur CASCADE;
CREATE TABLE public.cur (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	curso varchar(150),
	paralelo character varying(50) NOT NULL,
	gra_id integer NOT NULL,
	aula varchar(50),
	capacidad smallint,
	gestion smallint NOT NULL,
	creado date NOT NULL,
	act date NOT NULL,
	CONSTRAINT cur_pk PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.cur OWNER TO uaded;
-- ddl-end --

-- -- object: public.cur_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.cur_id_seq CASCADE;
-- CREATE SEQUENCE public.cur_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.cur_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.cal | type: TABLE --
-- DROP TABLE IF EXISTS public.cal CASCADE;
CREATE TABLE public.cal (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	ins_id integer NOT NULL,
	mat_id integer NOT NULL,
	nota1 smallint NOT NULL,
	nota2 smallint NOT NULL,
	nota3 smallint NOT NULL,
	nota_final numeric(5,1) NOT NULL,
	nota_aprob smallint NOT NULL,
	aprobado boolean,
	obs varchar(150),
	creado date NOT NULL,
	act date NOT NULL,
	CONSTRAINT cal_pk PRIMARY KEY (id)

);
-- ddl-end --
COMMENT ON TABLE public.cal IS E'SEGuimiento académico';
-- ddl-end --
ALTER TABLE public.cal OWNER TO uaded;
-- ddl-end --

-- -- object: public.seg_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.seg_id_seq CASCADE;
-- CREATE SEQUENCE public.seg_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.seg_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.pro | type: TABLE --
-- DROP TABLE IF EXISTS public.pro CASCADE;
CREATE TABLE public.pro (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	nombre character varying(100) NOT NULL,
	paterno character varying(50),
	materno varchar(50),
	formacion character varying(100),
	activo boolean NOT NULL,
	creado date NOT NULL,
	act date NOT NULL,
	CONSTRAINT pro_pk PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.pro OWNER TO uaded;
-- ddl-end --

-- -- object: public.pro_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.pro_id_seq CASCADE;
-- CREATE SEQUENCE public.pro_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.pro_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.asi | type: TABLE --
-- DROP TABLE IF EXISTS public.asi CASCADE;
CREATE TABLE public.asi (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	cur_id integer NOT NULL,
	mat_id integer NOT NULL,
	pro_id integer NOT NULL,
	creado date NOT NULL,
	act date NOT NULL,
	CONSTRAINT asi_pk PRIMARY KEY (id)

);
-- ddl-end --
COMMENT ON TABLE public.asi IS E'prof ASIgnado (enseña) a un curso y descripción de materias asignadas';
-- ddl-end --
ALTER TABLE public.asi OWNER TO uaded;
-- ddl-end --

-- -- object: public.asi_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.asi_id_seq CASCADE;
-- CREATE SEQUENCE public.asi_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.asi_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.pag | type: TABLE --
-- DROP TABLE IF EXISTS public.pag CASCADE;
CREATE TABLE public.pag (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	ins_id integer NOT NULL,
	nro_cuota smallint NOT NULL,
	cuota double precision NOT NULL,
	pagado boolean,
	metodo_pago varchar(50),
	nro_comprobante varchar(50),
	obs character varying(100),
	creado date NOT NULL,
	act date NOT NULL
);
-- ddl-end --
ALTER TABLE public.pag OWNER TO uaded;
-- ddl-end --

-- -- object: public.pag_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.pag_id_seq CASCADE;
-- CREATE SEQUENCE public.pag_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.pag_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.cos | type: TABLE --
-- DROP TABLE IF EXISTS public.cos CASCADE;
CREATE TABLE public.cos (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	cur_id integer NOT NULL,
	nro_cuota smallint NOT NULL,
	cuota numeric(10,2) NOT NULL,
	obs character varying(200) NOT NULL,
	creado date NOT NULL,
	act date NOT NULL,
	CONSTRAINT cos_pk PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.cos OWNER TO uaded;
-- ddl-end --

-- -- object: public.cos_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.cos_id_seq CASCADE;
-- CREATE SEQUENCE public.cos_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.cos_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.ges | type: TABLE --
-- DROP TABLE IF EXISTS public.ges CASCADE;
CREATE TABLE public.ges (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	gestion smallint,
	plan varchar(150) NOT NULL,
	inicio date NOT NULL,
	fin date NOT NULL,
	activo boolean NOT NULL,
	creado date NOT NULL,
	act date NOT NULL,
	CONSTRAINT ges_pk PRIMARY KEY (id)

);
-- ddl-end --
-- ALTER TABLE public.ges OWNER TO postgres;
-- ddl-end --

-- object: ges_fk | type: CONSTRAINT --
-- ALTER TABLE public.gra DROP CONSTRAINT IF EXISTS ges_fk CASCADE;
ALTER TABLE public.gra ADD CONSTRAINT ges_fk FOREIGN KEY (id_ges)
REFERENCES public.ges (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: mat_id_gra_fkey | type: CONSTRAINT --
-- ALTER TABLE public.mat DROP CONSTRAINT IF EXISTS mat_id_gra_fkey CASCADE;
ALTER TABLE public.mat ADD CONSTRAINT mat_id_gra_fkey FOREIGN KEY (gra_id)
REFERENCES public.gra (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: alu_fk | type: CONSTRAINT --
-- ALTER TABLE public.ins DROP CONSTRAINT IF EXISTS alu_fk CASCADE;
ALTER TABLE public.ins ADD CONSTRAINT alu_fk FOREIGN KEY (est_id)
REFERENCES public.est (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: cur_fk | type: CONSTRAINT --
-- ALTER TABLE public.ins DROP CONSTRAINT IF EXISTS cur_fk CASCADE;
ALTER TABLE public.ins ADD CONSTRAINT cur_fk FOREIGN KEY (cur_id)
REFERENCES public.cur (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: gra_fk | type: CONSTRAINT --
-- ALTER TABLE public.cur DROP CONSTRAINT IF EXISTS gra_fk CASCADE;
ALTER TABLE public.cur ADD CONSTRAINT gra_fk FOREIGN KEY (gra_id)
REFERENCES public.gra (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: ins_fk | type: CONSTRAINT --
-- ALTER TABLE public.cal DROP CONSTRAINT IF EXISTS ins_fk CASCADE;
ALTER TABLE public.cal ADD CONSTRAINT ins_fk FOREIGN KEY (ins_id)
REFERENCES public.ins (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: pro_fk | type: CONSTRAINT --
-- ALTER TABLE public.asi DROP CONSTRAINT IF EXISTS pro_fk CASCADE;
ALTER TABLE public.asi ADD CONSTRAINT pro_fk FOREIGN KEY (pro_id)
REFERENCES public.pro (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: cur_fk | type: CONSTRAINT --
-- ALTER TABLE public.asi DROP CONSTRAINT IF EXISTS cur_fk CASCADE;
ALTER TABLE public.asi ADD CONSTRAINT cur_fk FOREIGN KEY (cur_id)
REFERENCES public.cur (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: mat_fk | type: CONSTRAINT --
-- ALTER TABLE public.asi DROP CONSTRAINT IF EXISTS mat_fk CASCADE;
ALTER TABLE public.asi ADD CONSTRAINT mat_fk FOREIGN KEY (mat_id)
REFERENCES public.mat (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: insc_fk | type: CONSTRAINT --
-- ALTER TABLE public.pag DROP CONSTRAINT IF EXISTS insc_fk CASCADE;
ALTER TABLE public.pag ADD CONSTRAINT insc_fk FOREIGN KEY (ins_id)
REFERENCES public.ins (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: cur_fk | type: CONSTRAINT --
-- ALTER TABLE public.cos DROP CONSTRAINT IF EXISTS cur_fk CASCADE;
ALTER TABLE public.cos ADD CONSTRAINT cur_fk FOREIGN KEY (cur_id)
REFERENCES public.cur (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --


---auth---
-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler  version: 0.9.2
-- PostgreSQL version: 12.0
-- Project Site: pgmodeler.io
-- Model Author: ---


-- Database creation must be done outside a multicommand file.
-- These commands were put in this file only as a convenience.
-- -- object: authtest | type: DATABASE --
-- -- DROP DATABASE IF EXISTS authtest;
-- CREATE DATABASE authtest
-- 	ENCODING = 'UTF8'
-- 	LC_COLLATE = 'en_US.UTF-8'
-- 	LC_CTYPE = 'en_US.UTF-8'
-- 	TABLESPACE = pg_default
-- 	OWNER = postgres;
-- -- ddl-end --
--

-- object: public.usr_id_seq | type: SEQUENCE --
-- DROP SEQUENCE IF EXISTS public.usr_id_seq CASCADE;
CREATE SEQUENCE public.usr_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START WITH 1
	CACHE 1
	NO CYCLE
	OWNED BY NONE;
-- ddl-end --
ALTER SEQUENCE public.usr_id_seq OWNER TO uaded;
-- ddl-end --

-- object: public.usr | type: TABLE --
-- DROP TABLE IF EXISTS public.usr CASCADE;
CREATE TABLE public.usr (
	id integer NOT NULL DEFAULT nextval('public.usr_id_seq'::regclass),
	usuario character varying(80) NOT NULL,
	email character varying(120) NOT NULL,
	password character varying(255) NOT NULL,
	activo boolean,
	ultimo_ingreso date NOT NULL,
	creado timestamp,
	act timestamp,
	CONSTRAINT usr_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.usr OWNER TO uaded;
-- ddl-end --

-- object: ix_usr_usuario | type: INDEX --
-- DROP INDEX IF EXISTS public.ix_usr_usuario CASCADE;
CREATE UNIQUE INDEX ix_usr_usuario ON public.usr
	USING btree
	(
	  usuario
	)
	WITH (FILLFACTOR = 90);
-- ddl-end --

-- object: public.rol_id_seq | type: SEQUENCE --
-- DROP SEQUENCE IF EXISTS public.rol_id_seq CASCADE;
CREATE SEQUENCE public.rol_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START WITH 1
	CACHE 1
	NO CYCLE
	OWNED BY NONE;
-- ddl-end --
ALTER SEQUENCE public.rol_id_seq OWNER TO uaded;
-- ddl-end --

-- object: public.rol | type: TABLE --
-- DROP TABLE IF EXISTS public.rol CASCADE;
CREATE TABLE public.rol (
	id integer NOT NULL DEFAULT nextval('public.rol_id_seq'::regclass),
	rol character varying(50) NOT NULL,
	descripcion character varying(255),
	creado timestamp,
	act date,
	CONSTRAINT rol_pkey PRIMARY KEY (id),
	CONSTRAINT rol_rol_key UNIQUE (rol)

);
-- ddl-end --
ALTER TABLE public.rol OWNER TO uaded;
-- ddl-end --

-- object: public.per_id_seq | type: SEQUENCE --
-- DROP SEQUENCE IF EXISTS public.per_id_seq CASCADE;
CREATE SEQUENCE public.per_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START WITH 1
	CACHE 1
	NO CYCLE
	OWNED BY NONE;
-- ddl-end --
ALTER SEQUENCE public.per_id_seq OWNER TO uaded;
-- ddl-end --

-- object: public.per | type: TABLE --
-- DROP TABLE IF EXISTS public.per CASCADE;
CREATE TABLE public.per (
	id integer NOT NULL DEFAULT nextval('public.per_id_seq'::regclass),
	permiso character varying(50) NOT NULL,
	descripcion character varying(255),
	creado timestamp,
	act timestamp,
	CONSTRAINT per_pkey PRIMARY KEY (id),
	CONSTRAINT per_permiso_key UNIQUE (permiso)

);
-- ddl-end --
ALTER TABLE public.per OWNER TO uaded;
-- ddl-end --

-- object: public.usr_rol | type: TABLE --
-- DROP TABLE IF EXISTS public.usr_rol CASCADE;
CREATE TABLE public.usr_rol (
	usr_id integer NOT NULL,
	rol_id integer NOT NULL,
	CONSTRAINT usr_rol_pkey PRIMARY KEY (usr_id,rol_id)

);
-- ddl-end --
ALTER TABLE public.usr_rol OWNER TO uaded;
-- ddl-end --

-- object: public.rol_per | type: TABLE --
-- DROP TABLE IF EXISTS public.rol_per CASCADE;
CREATE TABLE public.rol_per (
	rol_id integer NOT NULL,
	per_id integer NOT NULL,
	CONSTRAINT rol_per_pkey PRIMARY KEY (rol_id,per_id)

);
-- ddl-end --
ALTER TABLE public.rol_per OWNER TO uaded;
-- ddl-end --

-- object: usr_rol_usr_id_fkey | type: CONSTRAINT --
-- ALTER TABLE public.usr_rol DROP CONSTRAINT IF EXISTS usr_rol_usr_id_fkey CASCADE;
ALTER TABLE public.usr_rol ADD CONSTRAINT usr_rol_usr_id_fkey FOREIGN KEY (usr_id)
REFERENCES public.usr (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: usr_rol_rol_id_fkey | type: CONSTRAINT --
-- ALTER TABLE public.usr_rol DROP CONSTRAINT IF EXISTS usr_rol_rol_id_fkey CASCADE;
ALTER TABLE public.usr_rol ADD CONSTRAINT usr_rol_rol_id_fkey FOREIGN KEY (rol_id)
REFERENCES public.rol (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: rol_per_rol_id_fkey | type: CONSTRAINT --
-- ALTER TABLE public.rol_per DROP CONSTRAINT IF EXISTS rol_per_rol_id_fkey CASCADE;
ALTER TABLE public.rol_per ADD CONSTRAINT rol_per_rol_id_fkey FOREIGN KEY (rol_id)
REFERENCES public.rol (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: rol_per_per_id_fkey | type: CONSTRAINT --
-- ALTER TABLE public.rol_per DROP CONSTRAINT IF EXISTS rol_per_per_id_fkey CASCADE;
ALTER TABLE public.rol_per ADD CONSTRAINT rol_per_per_id_fkey FOREIGN KEY (per_id)
REFERENCES public.per (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --




