-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler  version: 0.9.2
-- PostgreSQL version: 12.0
-- Project Site: pgmodeler.io
-- Model Author: ---

-- object: appgeo | type: ROLE --
-- DROP ROLE IF EXISTS appgeo;
CREATE ROLE appgeo WITH 
	INHERIT
	LOGIN
	ENCRYPTED PASSWORD '********';
-- ddl-end --

-- object: flask_user | type: ROLE --
-- DROP ROLE IF EXISTS flask_user;
CREATE ROLE flask_user WITH 
	INHERIT
	LOGIN
	ENCRYPTED PASSWORD '********';
-- ddl-end --

-- object: uaded | type: ROLE --
-- DROP ROLE IF EXISTS uaded;
CREATE ROLE uaded WITH 
	INHERIT
	LOGIN
	ENCRYPTED PASSWORD '********';
-- ddl-end --


-- Database creation must be done outside a multicommand file.
-- These commands were put in this file only as a convenience.
-- -- object: dbaded1 | type: DATABASE --
-- -- DROP DATABASE IF EXISTS dbaded1;
-- CREATE DATABASE dbaded1
-- 	ENCODING = 'UTF8'
-- 	LC_COLLATE = 'en_US.UTF-8'
-- 	LC_CTYPE = 'en_US.UTF-8'
-- 	TABLESPACE = pg_default
-- 	OWNER = uaded;
-- -- ddl-end --
-- 

-- object: public.plan | type: TABLE --
-- DROP TABLE IF EXISTS public.plan CASCADE;
CREATE TABLE public.plan (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	plan character varying(150) NOT NULL,
	CONSTRAINT plan_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.plan OWNER TO uaded;
-- ddl-end --

-- -- object: public.plan_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.plan_id_seq CASCADE;
-- CREATE SEQUENCE public.plan_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.plan_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.nivel | type: TABLE --
-- DROP TABLE IF EXISTS public.nivel CASCADE;
CREATE TABLE public.nivel (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	nivel character varying(255) NOT NULL,
	id_plan integer NOT NULL,
	CONSTRAINT nivel_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.nivel OWNER TO uaded;
-- ddl-end --

-- -- object: public.nivel_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.nivel_id_seq CASCADE;
-- CREATE SEQUENCE public.nivel_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.nivel_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.grado | type: TABLE --
-- DROP TABLE IF EXISTS public.grado CASCADE;
CREATE TABLE public.grado (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	grado character varying(255) NOT NULL,
	id_nivel integer NOT NULL,
	CONSTRAINT grado_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.grado OWNER TO uaded;
-- ddl-end --

-- -- object: public.grado_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.grado_id_seq CASCADE;
-- CREATE SEQUENCE public.grado_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.grado_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.materia | type: TABLE --
-- DROP TABLE IF EXISTS public.materia CASCADE;
CREATE TABLE public.materia (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	materia character varying(150) NOT NULL,
	id_grado integer NOT NULL,
	CONSTRAINT materia_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.materia OWNER TO uaded;
-- ddl-end --

-- -- object: public.materia_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.materia_id_seq CASCADE;
-- CREATE SEQUENCE public.materia_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.materia_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.alum | type: TABLE --
-- DROP TABLE IF EXISTS public.alum CASCADE;
CREATE TABLE public.alum (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	nombre varchar(100) NOT NULL,
	paterno varchar(100) NOT NULL,
	CONSTRAINT alum_pk PRIMARY KEY (id)

);
-- ddl-end --
-- ALTER TABLE public.alum OWNER TO postgres;
-- ddl-end --

-- object: public.inscripcion | type: TABLE --
-- DROP TABLE IF EXISTS public.inscripcion CASCADE;
CREATE TABLE public.inscripcion (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	id_alum integer,
	id_curso integer,
	CONSTRAINT inscripcion_pk PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.inscripcion OWNER TO uaded;
-- ddl-end --

-- object: public.curso | type: TABLE --
-- DROP TABLE IF EXISTS public.curso CASCADE;
CREATE TABLE public.curso (
	id integer NOT NULL GENERATED ALWAYS AS IDENTITY ,
	paralelo varchar(50),
	id_grado integer,
	id_grado1 integer NOT NULL,
	CONSTRAINT curso_pk PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.curso OWNER TO uaded;
-- ddl-end --

-- object: grado_fk | type: CONSTRAINT --
-- ALTER TABLE public.curso DROP CONSTRAINT IF EXISTS grado_fk CASCADE;
ALTER TABLE public.curso ADD CONSTRAINT grado_fk FOREIGN KEY (id_grado1)
REFERENCES public.grado (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: alum_fk | type: CONSTRAINT --
-- ALTER TABLE public.inscripcion DROP CONSTRAINT IF EXISTS alum_fk CASCADE;
ALTER TABLE public.inscripcion ADD CONSTRAINT alum_fk FOREIGN KEY (id_alum)
REFERENCES public.alum (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: inscripcion_uq | type: CONSTRAINT --
-- ALTER TABLE public.inscripcion DROP CONSTRAINT IF EXISTS inscripcion_uq CASCADE;
ALTER TABLE public.inscripcion ADD CONSTRAINT inscripcion_uq UNIQUE (id_alum);
-- ddl-end --

-- object: curso_fk | type: CONSTRAINT --
-- ALTER TABLE public.inscripcion DROP CONSTRAINT IF EXISTS curso_fk CASCADE;
ALTER TABLE public.inscripcion ADD CONSTRAINT curso_fk FOREIGN KEY (id_curso)
REFERENCES public.curso (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: nivel_id_plan_fkey | type: CONSTRAINT --
-- ALTER TABLE public.nivel DROP CONSTRAINT IF EXISTS nivel_id_plan_fkey CASCADE;
ALTER TABLE public.nivel ADD CONSTRAINT nivel_id_plan_fkey FOREIGN KEY (id_plan)
REFERENCES public.plan (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: grado_id_nivel_fkey | type: CONSTRAINT --
-- ALTER TABLE public.grado DROP CONSTRAINT IF EXISTS grado_id_nivel_fkey CASCADE;
ALTER TABLE public.grado ADD CONSTRAINT grado_id_nivel_fkey FOREIGN KEY (id_nivel)
REFERENCES public.nivel (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: materia_id_grado_fkey | type: CONSTRAINT --
-- ALTER TABLE public.materia DROP CONSTRAINT IF EXISTS materia_id_grado_fkey CASCADE;
ALTER TABLE public.materia ADD CONSTRAINT materia_id_grado_fkey FOREIGN KEY (id_grado)
REFERENCES public.grado (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --


