-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler  version: 0.9.2
-- PostgreSQL version: 12.0
-- Project Site: pgmodeler.io
-- Model Author: ---

-- object: uaded | type: ROLE --
-- DROP ROLE IF EXISTS uaded;
CREATE ROLE uaded WITH 
	INHERIT
	LOGIN
	UNENCRYPTED PASSWORD '********';
-- ddl-end --


-- Database creation must be done outside a multicommand file.
-- These commands were put in this file only as a convenience.
-- -- object: dbaded | type: DATABASE --
-- -- DROP DATABASE IF EXISTS dbaded;
-- CREATE DATABASE dbaded
-- 	ENCODING = 'UTF8'
-- 	LC_COLLATE = 'en_US.UTF-8'
-- 	LC_CTYPE = 'en_US.UTF-8'
-- 	TABLESPACE = pg_default
-- 	OWNER = uaded;
-- -- ddl-end --
-- 

-- object: public.plan | type: TABLE --
-- DROP TABLE IF EXISTS public.plan CASCADE;
CREATE TABLE public.plan (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	plan character varying(150) NOT NULL,
	CONSTRAINT plan_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.plan OWNER TO uaded;
-- ddl-end --

-- -- object: public.plan_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.plan_id_seq CASCADE;
-- CREATE SEQUENCE public.plan_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.plan_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.niv | type: TABLE --
-- DROP TABLE IF EXISTS public.niv CASCADE;
CREATE TABLE public.niv (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	nivel character varying(255) NOT NULL,
	plan_id integer NOT NULL,
	CONSTRAINT niv_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.niv OWNER TO uaded;
-- ddl-end --

-- -- object: public.niv_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.niv_id_seq CASCADE;
-- CREATE SEQUENCE public.niv_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.niv_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.gra | type: TABLE --
-- DROP TABLE IF EXISTS public.gra CASCADE;
CREATE TABLE public.gra (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	grado character varying(255) NOT NULL,
	niv_id integer NOT NULL,
	CONSTRAINT gra_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.gra OWNER TO uaded;
-- ddl-end --

-- -- object: public.gra_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.gra_id_seq CASCADE;
-- CREATE SEQUENCE public.gra_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.gra_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.mat | type: TABLE --
-- DROP TABLE IF EXISTS public.mat CASCADE;
CREATE TABLE public.mat (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	materia character varying(150) NOT NULL,
	gra_id integer NOT NULL,
	CONSTRAINT mat_pkey PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.mat OWNER TO uaded;
-- ddl-end --

-- -- object: public.mat_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.mat_id_seq CASCADE;
-- CREATE SEQUENCE public.mat_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.mat_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.alum | type: TABLE --
-- DROP TABLE IF EXISTS public.alum CASCADE;
CREATE TABLE public.alum (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	nombre character varying(100) NOT NULL,
	apellido character varying(100) NOT NULL,
	CONSTRAINT alum_pk PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.alum OWNER TO uaded;
-- ddl-end --

-- -- object: public.alum_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.alum_id_seq CASCADE;
-- CREATE SEQUENCE public.alum_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.alum_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.insc | type: TABLE --
-- DROP TABLE IF EXISTS public.insc CASCADE;
CREATE TABLE public.insc (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 ),
	alum_id integer,
	cur_id integer,
	fecha_insc date,
	CONSTRAINT insc_pk PRIMARY KEY (id),
	CONSTRAINT insc_uq UNIQUE (alum_id)

);
-- ddl-end --
ALTER TABLE public.insc OWNER TO uaded;
-- ddl-end --

-- -- object: public.inscripcion_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.inscripcion_id_seq CASCADE;
-- CREATE SEQUENCE public.inscripcion_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.inscripcion_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.cur | type: TABLE --
-- DROP TABLE IF EXISTS public.cur CASCADE;
CREATE TABLE public.cur (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	gra_id integer NOT NULL,
	paralelo character varying(50),
	gestion smallint,
	fecha_ini date,
	fecha_fin date,
	CONSTRAINT cur_pk PRIMARY KEY (id)

);
-- ddl-end --
COMMENT ON COLUMN public.cur.fecha_ini IS E'con datos cuando es diferente a una gestión anual';
-- ddl-end --
COMMENT ON COLUMN public.cur.fecha_fin IS E'con datos cuando es diferente a una gestión anual';
-- ddl-end --
ALTER TABLE public.cur OWNER TO uaded;
-- ddl-end --

-- -- object: public.cur_id_seq | type: SEQUENCE --
-- -- DROP SEQUENCE IF EXISTS public.cur_id_seq CASCADE;
-- CREATE SEQUENCE public.cur_id_seq
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	MAXVALUE 2147483647
-- 	START WITH 1
-- 	CACHE 1
-- 	NO CYCLE
-- 	OWNED BY NONE;
-- -- ddl-end --
-- ALTER SEQUENCE public.cur_id_seq OWNER TO uaded;
-- -- ddl-end --
-- 
-- object: public.seg | type: TABLE --
-- DROP TABLE IF EXISTS public.seg CASCADE;
CREATE TABLE public.seg (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	insc_id integer NOT NULL,
	alum_id integer NOT NULL,
	mat_id smallint NOT NULL,
	ev01 smallint,
	ev02 smallint,
	ev03 smallint,
	evfin smallint,
	aprob boolean,
	CONSTRAINT seg_pk PRIMARY KEY (id)

);
-- ddl-end --
COMMENT ON TABLE public.seg IS E'SEGuimiento académico';
-- ddl-end --
COMMENT ON COLUMN public.seg.mat_id IS E'asignado a partir de INSC/CURSO/ASIG.id_mat';
-- ddl-end --
ALTER TABLE public.seg OWNER TO uaded;
-- ddl-end --

-- object: public.prof | type: TABLE --
-- DROP TABLE IF EXISTS public.prof CASCADE;
CREATE TABLE public.prof (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	nombre varchar(100),
	apellido varchar(100),
	formacion varchar(100),
	CONSTRAINT prof_pk PRIMARY KEY (id)

);
-- ddl-end --
ALTER TABLE public.prof OWNER TO uaded;
-- ddl-end --

-- object: public.asig | type: TABLE --
-- DROP TABLE IF EXISTS public.asig CASCADE;
CREATE TABLE public.asig (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	cur_id integer NOT NULL,
	mat_id integer NOT NULL,
	prof_id integer NOT NULL,
	CONSTRAINT asig_pk PRIMARY KEY (id)

);
-- ddl-end --
COMMENT ON TABLE public.asig IS E'prof ASIGnado (enseña) a un curso y descripción de materias asignadas';
-- ddl-end --
ALTER TABLE public.asig OWNER TO uaded;
-- ddl-end --

-- object: prof_fk | type: CONSTRAINT --
-- ALTER TABLE public.asig DROP CONSTRAINT IF EXISTS prof_fk CASCADE;
ALTER TABLE public.asig ADD CONSTRAINT prof_fk FOREIGN KEY (prof_id)
REFERENCES public.prof (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: cur_fk | type: CONSTRAINT --
-- ALTER TABLE public.asig DROP CONSTRAINT IF EXISTS cur_fk CASCADE;
ALTER TABLE public.asig ADD CONSTRAINT cur_fk FOREIGN KEY (cur_id)
REFERENCES public.cur (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: mat_fk | type: CONSTRAINT --
-- ALTER TABLE public.asig DROP CONSTRAINT IF EXISTS mat_fk CASCADE;
ALTER TABLE public.asig ADD CONSTRAINT mat_fk FOREIGN KEY (mat_id)
REFERENCES public.mat (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: insc_fk | type: CONSTRAINT --
-- ALTER TABLE public.seg DROP CONSTRAINT IF EXISTS insc_fk CASCADE;
ALTER TABLE public.seg ADD CONSTRAINT insc_fk FOREIGN KEY (insc_id)
REFERENCES public.insc (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: niv_id_plan_fkey | type: CONSTRAINT --
-- ALTER TABLE public.niv DROP CONSTRAINT IF EXISTS niv_id_plan_fkey CASCADE;
ALTER TABLE public.niv ADD CONSTRAINT niv_id_plan_fkey FOREIGN KEY (plan_id)
REFERENCES public.plan (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: gra_id_niv_fkey | type: CONSTRAINT --
-- ALTER TABLE public.gra DROP CONSTRAINT IF EXISTS gra_id_niv_fkey CASCADE;
ALTER TABLE public.gra ADD CONSTRAINT gra_id_niv_fkey FOREIGN KEY (niv_id)
REFERENCES public.niv (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: mat_id_gra_fkey | type: CONSTRAINT --
-- ALTER TABLE public.mat DROP CONSTRAINT IF EXISTS mat_id_gra_fkey CASCADE;
ALTER TABLE public.mat ADD CONSTRAINT mat_id_gra_fkey FOREIGN KEY (gra_id)
REFERENCES public.gra (id) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: alum_fk | type: CONSTRAINT --
-- ALTER TABLE public.insc DROP CONSTRAINT IF EXISTS alum_fk CASCADE;
ALTER TABLE public.insc ADD CONSTRAINT alum_fk FOREIGN KEY (alum_id)
REFERENCES public.alum (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: cur_fk | type: CONSTRAINT --
-- ALTER TABLE public.insc DROP CONSTRAINT IF EXISTS cur_fk CASCADE;
ALTER TABLE public.insc ADD CONSTRAINT cur_fk FOREIGN KEY (cur_id)
REFERENCES public.cur (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: gra_fk | type: CONSTRAINT --
-- ALTER TABLE public.cur DROP CONSTRAINT IF EXISTS gra_fk CASCADE;
ALTER TABLE public.cur ADD CONSTRAINT gra_fk FOREIGN KEY (gra_id)
REFERENCES public.gra (id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --


