--

CREATE TABLE public.grado (
    id integer NOT NULL,
    grado character varying(255) NOT NULL,
    id_nivel integer NOT NULL
);



ALTER TABLE public.grado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.materia (
    id integer NOT NULL,
    materia character varying(150) NOT NULL,
    id_grado integer NOT NULL
);



ALTER TABLE public.materia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.nivel (
    id integer NOT NULL,
    nivel character varying(255) NOT NULL,
    id_plan integer NOT NULL
);


--
-- TOC entry 204 (class 1259 OID 72566)
-- Name: nivel_id_seq; Type: SEQUENCE; Schema: public; Owner: uaded
--

ALTER TABLE public.nivel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nivel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.plan (
    id integer NOT NULL,
    plan character varying(150) NOT NULL
);



ALTER TABLE public.plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--fk
ALTER TABLE ONLY public.nivel
   ADD CONSTRAINT nivel_id_plan_fkey FOREIGN KEY (id_plan) 
   REFERENCES public.plan(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.grado
   ADD CONSTRAINT grado_id_nivel_fkey FOREIGN KEY (id_nivel) 
   REFERENCES public.nivel(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.materia
   ADD CONSTRAINT materia_id_grado_fkey FOREIGN KEY (id_grado) 
   REFERENCES public.grado(id) ON UPDATE CASCADE ON DELETE RESTRICT;

